RMC-141
ONSdigital/census-rm-qid-batch-runner pull request #2
Opened 2019-05-22 13:45 UTC by rjweeks

# Motivation and Context
Add a script to generate the unaddressed QIC/UAC pairs print files.

# What has changed
A new script has been added. 
A new Pod description has been added to run the script from.

# How to test?
Please see changes to Readme.

# Links
https://trello.com/c/tFx0hjmx/646-rmc-141-unaddressed-ccs-print-file-exporter-13

2019-05-28 08:25 UTC, AdamHawtin submitted a review, later dismissed
Tests are failing on linting, also needs to generate manifest files there may also be a requirement for one of the product pack codes to have an additional welsh qid pair.

2019-05-28 08:25 UTC, AdamHawtin commented on README.md
> +You will need to add the Role 'Storage Admin' to the GCP Project Compute Engine Service Account.
This change should probably be terraformed if we do it.

Also I think it's important to note that when used like this the gcloud module is finding and using whatever gcloud config exists in the environment it's running in, it may be convenient not having to supply all the config but it could lead to unexpected results if we don't keep track.

2019-05-28 08:25 UTC, AdamHawtin commented on generate_print_file.py
> +    db_password_file = open("/root/.db-credentials/password", "r")
It would make the script a lot easier to test locally if these were read from environment variables rather than files.

2019-05-28 08:25 UTC, AdamHawtin commented on generate_print_file.py
> +    db_host=os.getenv('db_host', 'NoValue')
Why do these have a default string? Could use `os.environ['VAR']` so that it fails with an exception if the value isn't set.

2019-05-28 08:25 UTC, AdamHawtin commented on generate_print_file.py
> +def copy_printfiles_to_gcs():
Could store and pass the list of files generated to this function, otherwise it can upload files from a previous run.

2019-05-28 08:26 UTC, AdamHawtin commented on qid-batch-runner.yml
> +      image: eu.gcr.io/census-rm-richardweeks01/census-rm-qid-batch-runner:latest
Still pointing at your GCP project.

2019-05-28 08:29 UTC, AdamHawtin commented on qid-batch-runner.yml
> +        - name: db_host
We use capitals for environment variables everywhere else.

2019-05-28 08:41 UTC, rjweeks commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-141 - Unaddressed & CCS print file exporter (13)](https://trello.com/c/tFx0hjmx/646-rmc-141-unaddressed-ccs-print-file-exporter-13)

2019-05-31 08:27 UTC, NickGrantONS commented on generate_print_files.py
> +    db_port = os.environ['DB_PORT']
These should all have default values so that this can be run locally easily

2019-05-31 08:27 UTC, NickGrantX requested changes
Doesn't run locally without configuring a load of environment variables

2019-06-03 08:52 UTC, liamtoozer approved these changes
LGTM 👍 Ran locally with the default unaddressed batch and got the expected output

2019-06-03 09:19 UTC, NickGrantX approved these changes
LGTM 👍

2019-06-03 09:59 UTC, merged