Add acceptance test for unaddressed print files
ONSdigital/census-rm-qid-batch-runner pull request #5
Opened 2019-06-06 14:47 UTC by liamtoozer

# Motivation and Context

We can avoid copying the unaddressed batch scripts in this repo across into the acceptance tests repo to run tests. Although the scripts are unlikely to change often, there is a still a danger of regression with having the same script in different locations.

To allow the acceptance tests to use the scripts in this repo, we have created a wrapper shell script which will test the expected unaddressed print files output. This shell script will be invoked 

# What has changed

* Created a bash script to invoke a small acceptance test (can be used locally and by k8s)
* Created an acceptance test script (to be invoked by the shell script)
* Added test batch file for acceptance test

# How to test?

### Locally
* Checkout this [acceptance test branch](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/67)
* Run `make test` 
* Ensure the acceptance test kicks off the test from this repo and passes

### In k8s
* Checkout this [acceptance test branch](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/67)
* From the acceptance tests repo branch, run:
```bash
BUILD=true IMAGE=eu.gcr.io/census-rm-<PROJECT_ID>/rm/census-rm-acceptance-tests  ENV=<PROJECT_ID> ./run_gke.sh
```
* Ensure the acceptance test kicks off the test from this repo and passes

# Links

https://trello.com/c/tT4XZ09B/784-acceptance-tests-for-unaddressed-print-files-13

2019-06-06 20:54 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Acceptance tests for unaddressed print files (13)](https://trello.com/c/tT4XZ09B/784-acceptance-tests-for-unaddressed-print-files-13)

2019-06-07 14:02 UTC, hbrace submitted a review, later dismissed

2019-06-07 15:55 UTC, NickGrantX approved these changes
Good stuff. The only thing you might consider is moving these scripts and stuff into a repo of their own, to keep the batch runner image 'pure' (i.e. not having any test scripts or test data in it)

2019-06-10 08:49 UTC, AdamHawtin commented on run_acceptance_tests.sh
> +sleep 15
We could consume uac created events until we reach the expected number here instead of hardcoding a wait.

2019-06-10 12:07 UTC, AdamHawtin submitted a review, later dismissed
A few suggestions, also see my comment on the acceptance tests repo PR about using a deployment kind to avoid having to hardcode the wait for the pod to start up.

2019-06-10 12:07 UTC, AdamHawtin commented on run_acceptance_tests.sh
> +BATCH_ID=${OUTPUT: -36}
It would be nicer to tie these steps together in the python test script rather than passing stuff around here

2019-06-12 09:15 UTC, jcox-dev requested changes
Had some issues as documented in https://github.com/ONSdigital/census-rm-acceptance-tests/pull/67

2019-06-13 07:11 UTC, jcox-dev approved these changes

2019-06-13 11:21 UTC, merged