Upgrading and Securing RabbitMQ
ONSdigital/census-rm-qid-batch-runner pull request #56
Opened 2021-01-14 17:59 UTC by apolloakora

# Motivation and Context

This change upgrades the RabbitMQ operator, it upgrades the RabbitMQ docker container versions and also delivers a gaggle of hardening and security features for the RabbitMQ cluster.

# What has changed

Changes are applied to the microservices, the tests, the docker development project and the central RabbitMQ provisioning code in the Kubernetes repository.

2021-01-14 18:01 UTC, apolloakora commented
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up Rabbit in all envs after account purge & lock down (8)](https://trello.com/c/HnYc3xh2/1796-clean-up-rabbit-in-all-envs-after-account-purge-lock-down-8)

2021-01-15 09:17 UTC, NickGrantONS requested changes
changing the default creds from guest/guest doesn't make things any more secure... it's just an annoying change in developer working practice, which will slow us down when working on features and bug fixes, I'm afraid.

2021-01-20 12:41 UTC, AdamHawtin approved these changes

2021-01-21 12:46 UTC, ryangrundy7 approved these changes

2021-01-21 14:58 UTC, apolloakora commented
> changing the default creds from guest/guest doesn't make things any more secure... it's just an annoying change in developer working practice, which will slow us down when working on features and bug fixes, I'm afraid.

Nick could you recheck this - guest/guest is still in place for the devs.

2021-01-21 15:00 UTC, NickGrantONS approved these changes

2021-01-22 15:52 UTC, merged